### ISSUE TITLE
packet serial

### ISSUE THREAD

**Issue by natxopedreira** [bakercp/ofxSerial#11]
I want to take a look at the packet serial example, but im not able to make it work.

Im using an arduino mega, uploading just the example, and im running OS X oF0.9, everything compiles and runs ok. 

The arduino example also upload to the board without issues, but i see no data coming back from the arduino, onSerialBuffer function never get called.

What can be wrong?

**Comment by bakercp** [comment]
... did you ever resolve this?  Sorry it took so long to respond.

**Comment by natxopedreira** [comment]
Hey, don't worry, just tried with an arduino Uno and get the same result, i ran out of time so take another aproach.....
