### ISSUE TITLE
Complie Error

### ISSUE THREAD

**Issue by kimyousuk** [bakercp/ofxSerial#21]
Dear bakercp

First, I`m sorry, I`m very new here.
```
pi@raspberrypi:~/openFrameworks/apps/myApps/etal $ make
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0
with PKG_CONFIG_LIBDIR=
Compiling OF library for Release
make[1]: Entering directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0
with PKG_CONFIG_LIBDIR=
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0
with PKG_CONFIG_LIBDIR=
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0
with PKG_CONFIG_LIBDIR=
Done!
make[1]: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'


Compiling etal for Release
make[1]: Entering directory '/home/pi/openFrameworks/apps/myApps/etal'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0
with PKG_CONFIG_LIBDIR=
Compiling /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp
g++ -c -O3 -DNDEBUG -Wall -Werror=return-type -std=c++14 -DGCC_HAS_REGEX -march=armv6 -mfpu=vfp -mfloat-abi=hard -fPIC -ftree-vectorize -Wno-psabi -pipe -DOF_USING_GTK -DTARGET_RASPBERRY_PI -DSTANDALONE -DPIC -D_REENTRANT -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -DTARGET_POSIX -DHAVE_LIBOPENMAX=2 -DOMX -DOMX_SKIP64BIT -DUSE_EXTERNAL_OMX -DHAVE_LIBBCM_HOST -DUSE_EXTERNAL_LIBBCM_HOST -DUSE_VCHIQ_ARM  -I/opt/vc/include -I/opt/vc/include/IL -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -pthread -D_REENTRANT -pthread -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -I/usr/include/gstreamer-1.0 -I/usr/include/AL -I/usr/include/arm-linux-gnueabihf -I/usr/include/rtaudio -I/usr/include/alsa -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/arm-linux-gnueabihf/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/libdrm -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib/arm-linux-gnueabihf/glib-2.0/include -I/home/pi/openFrameworks/libs/glm/include -I/home/pi/openFrameworks/libs/glm/include/glm -I/home/pi/openFrameworks/libs/glm/include/glm/simd -I/home/pi/openFrameworks/libs/glm/include/glm/gtx -I/home/pi/openFrameworks/libs/glm/include/glm/gtc -I/home/pi/openFrameworks/libs/glm/include/glm/detail -I/home/pi/openFrameworks/libs/json/include -I/home/pi/openFrameworks/libs/kiss/include -I/home/pi/openFrameworks/libs/tess2/include -I/home/pi/openFrameworks/libs/utf8/include -I/home/pi/openFrameworks/libs/utf8/include/utf8 -I/home/pi/openFrameworks/libs/openFrameworks -I/home/pi/openFrameworks/libs/openFrameworks/gl -I/home/pi/openFrameworks/libs/openFrameworks/3d -I/home/pi/openFrameworks/libs/openFrameworks/video -I/home/pi/openFrameworks/libs/openFrameworks/graphics -I/home/pi/openFrameworks/libs/openFrameworks/app -I/home/pi/openFrameworks/libs/openFrameworks/types -I/home/pi/openFrameworks/libs/openFrameworks/utils -I/home/pi/openFrameworks/libs/openFrameworks/events -I/home/pi/openFrameworks/libs/openFrameworks/sound -I/home/pi/openFrameworks/libs/openFrameworks/communication -I/home/pi/openFrameworks/libs/openFrameworks/math -I/home/pi/openFrameworks/apps/myApps/etal/src -I/home/pi/openFrameworks/addons/ofxPoco/src -Isrc -I/home/pi/openFrameworks/addons/ofxIO/src -I/home/pi/openFrameworks/addons/ofxIO/libs -I/home/pi/openFrameworks/addons/ofxIO/libs/ofxIO -I/home/pi/openFrameworks/addons/ofxIO/libs/ofxIO/include -I/home/pi/openFrameworks/addons/ofxIO/libs/ofxIO/include/ofx -I/home/pi/openFrameworks/addons/ofxIO/libs/ofxIO/include/ofx/IO -I/home/pi/openFrameworks/addons/ofxIO/libs/ofxIO/src -I/home/pi/openFrameworks/addons/ofxIO/libs/snappy -I/home/pi/openFrameworks/addons/ofxIO/libs/snappy/src -I/home/pi/openFrameworks/addons/ofxIO/libs/alphanum -I/home/pi/openFrameworks/addons/ofxIO/libs/alphanum/include -I/home/pi/openFrameworks/addons/ofxIO/libs/brotli -I/home/pi/openFrameworks/addons/ofxIO/libs/brotli/src -I/home/pi/openFrameworks/addons/ofxIO/libs/brotli/src/common -I/home/pi/openFrameworks/addons/ofxIO/libs/brotli/src/tools -I/home/pi/openFrameworks/addons/ofxIO/libs/brotli/src/enc -I/home/pi/openFrameworks/addons/ofxIO/libs/brotli/src/dec -I/home/pi/openFrameworks/addons/ofxIO/libs/lz4 -I/home/pi/openFrameworks/addons/ofxIO/libs/lz4/src -I/home/pi/openFrameworks/addons/ofxSerial/src -I/home/pi/openFrameworks/addons/ofxSerial/libs -I/home/pi/openFrameworks/addons/ofxSerial/libs/ofxSerial -I/home/pi/openFrameworks/addons/ofxSerial/libs/ofxSerial/include -I/home/pi/openFrameworks/addons/ofxSerial/libs/ofxSerial/include/ofx -I/home/pi/openFrameworks/addons/ofxSerial/libs/ofxSerial/include/ofx/IO -I/home/pi/openFrameworks/addons/ofxSerial/libs/ofxSerial/src -I/home/pi/openFrameworks/addons/ofxSerial/libs/serial -I/home/pi/openFrameworks/addons/ofxSerial/libs/serial/include -I/home/pi/openFrameworks/addons/ofxSerial/libs/serial/include/serial -I/home/pi/openFrameworks/addons/ofxSerial/libs/serial/include/serial/impl -I/home/pi/openFrameworks/addons/ofxSerial/libs/serial/src -I/home/pi/openFrameworks/addons/ofxSerial/libs/serial/src/impl -I/home/pi/openFrameworks/addons/ofxSerial/libs/serial/src/impl/list_ports -MMD -MP -MF obj/linuxarmv6l/Release/src/main.d -MT obj/linuxarmv6l/Release/src/main.o -o obj/linuxarmv6l/Release/src/main.o -c /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp
In file included from /home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.hpp:579,
                 from /home/pi/openFrameworks/libs/glm/include/glm/ext.hpp:48,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVectorMath.h:21,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:37,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl: In function ‘glm::vec2 glm::unpackUnorm2x8(glm::uint16)’:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl:377:37: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘glm::u8vec2’ {aka ‘struct glm::tvec2<unsigned char, (glm::precision)0>’} from an array of ‘glm::uint16’ {aka ‘short unsigned int’} [-Wclass-memaccess]
   memcpy(&Unpack, &p, sizeof(Unpack));
                                     ^
In file included from /home/pi/openFrameworks/libs/glm/include/glm/vec2.hpp:6,
                 from /home/pi/openFrameworks/libs/openFrameworks/events/ofEvents.h:8,
                 from /home/pi/openFrameworks/libs/openFrameworks/utils/ofURLFileLoader.h:3,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:11,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/detail/type_vec2.hpp:19:9: note: ‘glm::u8vec2’ {aka ‘struct glm::tvec2<unsigned char, (glm::precision)0>’} declared here
  struct tvec2
         ^~~~~
In file included from /home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.hpp:579,
                 from /home/pi/openFrameworks/libs/glm/include/glm/ext.hpp:48,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVectorMath.h:21,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:37,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl: In function ‘glm::vec2 glm::unpackSnorm2x8(glm::uint16)’:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl:409:37: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘glm::i8vec2’ {aka ‘struct glm::tvec2<signed char, (glm::precision)0>’} from an array of ‘glm::uint16’ {aka ‘short unsigned int’} [-Wclass-memaccess]
   memcpy(&Unpack, &p, sizeof(Unpack));
                                     ^
In file included from /home/pi/openFrameworks/libs/glm/include/glm/vec2.hpp:6,
                 from /home/pi/openFrameworks/libs/openFrameworks/events/ofEvents.h:8,
                 from /home/pi/openFrameworks/libs/openFrameworks/utils/ofURLFileLoader.h:3,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:11,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/detail/type_vec2.hpp:19:9: note: ‘glm::i8vec2’ {aka ‘struct glm::tvec2<signed char, (glm::precision)0>’} declared here
  struct tvec2
         ^~~~~
In file included from /home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.hpp:579,
                 from /home/pi/openFrameworks/libs/glm/include/glm/ext.hpp:48,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVectorMath.h:21,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:37,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl: In function ‘glm::vec4 glm::unpackUnorm4x16(glm::uint64)’:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl:437:37: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘glm::u16vec4’ {aka ‘struct glm::tvec4<short unsigned int, (glm::precision)0>’} from an array of ‘glm::uint64’ {aka ‘long long unsigned int’} [-Wclass-memaccess]
   memcpy(&Unpack, &p, sizeof(Unpack));
                                     ^
In file included from /home/pi/openFrameworks/libs/glm/include/glm/vec4.hpp:6,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVec4f.h:8,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVec3f.h:5,
                 from /home/pi/openFrameworks/libs/openFrameworks/types/ofPoint.h:3,
                 from /home/pi/openFrameworks/libs/openFrameworks/types/ofParameter.h:5,
                 from /home/pi/openFrameworks/libs/openFrameworks/utils/ofJson.h:4,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:21,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/detail/type_vec4.hpp:19:9: note: ‘glm::u16vec4’ {aka ‘struct glm::tvec4<short unsigned int, (glm::precision)0>’} declared here
  struct tvec4
         ^~~~~
In file included from /home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.hpp:579,
                 from /home/pi/openFrameworks/libs/glm/include/glm/ext.hpp:48,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVectorMath.h:21,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:37,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl: In function ‘glm::vec4 glm::unpackSnorm4x16(glm::uint64)’:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl:469:37: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘glm::i16vec4’ {aka ‘struct glm::tvec4<short int, (glm::precision)0>’} from an array of ‘glm::uint64’ {aka ‘long long unsigned int’} [-Wclass-memaccess]
   memcpy(&Unpack, &p, sizeof(Unpack));
                                     ^
In file included from /home/pi/openFrameworks/libs/glm/include/glm/vec4.hpp:6,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVec4f.h:8,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVec3f.h:5,
                 from /home/pi/openFrameworks/libs/openFrameworks/types/ofPoint.h:3,
                 from /home/pi/openFrameworks/libs/openFrameworks/types/ofParameter.h:5,
                 from /home/pi/openFrameworks/libs/openFrameworks/utils/ofJson.h:4,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:21,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/detail/type_vec4.hpp:19:9: note: ‘glm::i16vec4’ {aka ‘struct glm::tvec4<short int, (glm::precision)0>’} declared here
  struct tvec4
         ^~~~~
In file included from /home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.hpp:579,
                 from /home/pi/openFrameworks/libs/glm/include/glm/ext.hpp:48,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVectorMath.h:21,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:37,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl: In function ‘glm::vec4 glm::unpackHalf4x16(glm::uint64)’:
/home/pi/openFrameworks/libs/glm/include/glm/./gtc/packing.inl:505:37: warning: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘glm::i16vec4’ {aka ‘struct glm::tvec4<short int, (glm::precision)0>’} from an array of ‘glm::uint64’ {aka ‘long long unsigned int’} [-Wclass-memaccess]
   memcpy(&Unpack, &v, sizeof(Unpack));
                                     ^
In file included from /home/pi/openFrameworks/libs/glm/include/glm/vec4.hpp:6,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVec4f.h:8,
                 from /home/pi/openFrameworks/libs/openFrameworks/math/ofVec3f.h:5,
                 from /home/pi/openFrameworks/libs/openFrameworks/types/ofPoint.h:3,
                 from /home/pi/openFrameworks/libs/openFrameworks/types/ofParameter.h:5,
                 from /home/pi/openFrameworks/libs/openFrameworks/utils/ofJson.h:4,
                 from /home/pi/openFrameworks/libs/openFrameworks/ofMain.h:21,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:1:
/home/pi/openFrameworks/libs/glm/include/glm/detail/type_vec4.hpp:19:9: note: ‘glm::i16vec4’ {aka ‘struct glm::tvec4<short int, (glm::precision)0>’} declared here
  struct tvec4
         ^~~~~
In file included from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:2:
/home/pi/openFrameworks/apps/myApps/etal/src/ofApp.h: At global scope:
/home/pi/openFrameworks/apps/myApps/etal/src/ofApp.h:26:28: error: cannot declare field ‘ofApp::device’ to be of abstract type ‘ofx::IO::PacketSerialDevice_<ofx::IO::COBSEncoding>’
  ofxIO::PacketSerialDevice device;
                            ^~~~~~
In file included from /home/pi/openFrameworks/addons/ofxSerial/src/ofxSerial.h:16,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/ofApp.h:4,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:2:
/home/pi/openFrameworks/addons/ofxSerial/libs/ofxSerial/include/ofx/IO/PacketSerialDevice.h:22:7: note:   because the following virtual functions are pure within ‘ofx::IO::PacketSerialDevice_<ofx::IO::COBSEncoding>’:
 class PacketSerialDevice_: protected BufferedSerialDevice
       ^~~~~~~~~~~~~~~~~~~
In file included from /home/pi/openFrameworks/addons/ofxIO/src/ofxIO.h:18,
                 from /home/pi/openFrameworks/addons/ofxSerial/src/ofxSerial.h:12,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/ofApp.h:4,
                 from /home/pi/openFrameworks/apps/myApps/etal/src/main.cpp:2:
/home/pi/openFrameworks/addons/ofxIO/libs/ofxIO/include/ofx/IO/AbstractTypes.h:107:25: note:    ‘virtual std::size_t ofx::IO::AbstractByteSink::writeBytes(std::initializer_list<unsigned char>)’
     virtual std::size_t writeBytes(std::initializer_list<uint8_t> bytes) = 0;
                         ^~~~~~~~~~
make[1]: *** [/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:223: obj/linuxarmv6l/Release/src/main.o] Error 1
make[1]: Leaving directory '/home/pi/openFrameworks/apps/myApps/etal'
make: *** [/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
```

I`ve got these error on Rpi3 B+ with Rasbian Lite.
I searched a lot, but I cannot solve this. Please, give me a little hint...

Thanks.

**Comment by bakercp** [comment]
What version of ofxSerial and ofxIO are you using?

**Comment by kimyousuk** [comment]
I installed Ofx Serial stable version and ofxIO master version. .... 

Thanks to reply...

**Comment by bakercp** [comment]
Versions need to be matched -- so if you install ofxSerial stable, you need
ofxIO stable.

Or, ofxSerial master, you need ofxIO master

---
https://new.christopherbaker.net

**Comment by kimyousuk** [comment]
at the first time, I look this article so I figure out Ofx compiling.
[https://forum.openframeworks.cc/t/rpi-4-raspbian-buster-openframeworks/32856/20](url)
So, I changed config.make. I just add `PROJECT_LDFLAGS += -latomic ` . 
then I recompiled.
add to addon(ofxSerial, ofxIO, etc). 
then. make addons.make file.
and make.

ps. first time, I used master version of ofxSerial and ofxIO. But, I have same problem.

**Comment by bakercp** [comment]
Hey, I'm sorry, ofxSerial master was out of sync with ofxIO master.

Can you try it again with the latest master branches from both projects?

Thanks!

---
https://new.christopherbaker.net

**Comment by kimyousuk** [comment]
I did both master branches(ofxSerial, oFxIO). Appeared to have been compiled, but finally got an error.
`Linking bin/etal for linuxarmv6l
g++ -o bin/etal  obj/linuxarmv6l/Release/src/main.o obj/linuxarmv6l/Release/src/ofApp.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxPoco/src/ofxXmlPoco.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBuffer.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/SearchPath.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/RecursiveDirectoryIteratorStategies.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/Thread.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ThreadsafeLoggerChannel.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/DirectoryFilter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/DeviceFilter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/FileExtensionFilter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/HexBinaryEncoding.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/RecursiveDirectoryIterator.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/PollingThread.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/Hash.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/JSONUtils.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/DirectoryWatcherManager.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/FilteredStreams.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/RegexPathFilter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/HiddenFileFilter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/PathFilterCollection.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/SLIPEncoding.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBufferStream.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBufferReader.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/DirectoryWatcher.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBufferWriter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ImageUtils.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/StreamFilters.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/BackoffStrategy.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/Base64Encoding.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/ByteBufferUtils.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/Compression.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/COBSEncoding.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/LinkFilter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/DirectoryUtils.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/ofxIO/src/URIEncoding.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/snappy/src/snappy-sinksource.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/snappy/src/snappy-stubs-internal.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/snappy/src/snappy-c.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/snappy/src/snappy.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/common/dictionary.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/compress_fragment_two_pass.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/memory.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/bit_cost.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/brotli_bit_stream.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/cluster.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/encode.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/backward_references.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/static_dict.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/compress_fragment.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/block_splitter.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/utf8_util.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/encode_parallel.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/streams.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/entropy_encode.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/literal_cost.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/metablock.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/compressor.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/enc/histogram.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/dec/decode.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/dec/bit_reader.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/dec/state.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/brotli/src/dec/huffman.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxIO/libs/lz4/src/lz4.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/ofxSerial/src/SerialDevice.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/ofxSerial/src/SerialEvents.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/ofxSerial/src/SerialDeviceUtils.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/ofxSerial/src/BufferedSerialDevice.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/serial/src/serial.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/serial/src/impl/list_ports/list_ports_win.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/serial/src/impl/list_ports/list_ports_osx.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/serial/src/impl/list_ports/list_ports_linux.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/serial/src/impl/win.o /home/pi/openFrameworks/addons/obj/linuxarmv6l/Release/ofxSerial/libs/serial/src/impl/unix.o  /home/pi/openFrameworks/libs/openFrameworksCompiled/lib/linuxarmv6l/libopenFrameworks.a   -Wl,-rpath=./libs:./bin/libs -Wl,--as-needed -Wl,--gc-sections -pthread -latomic -L/opt/vc/lib -lPocoNetSSL -lPocoNet -lPocoCrypto -lPocoUtil -lPocoXML -lPocoFoundation -lcrypto -lssl /home/pi/openFrameworks/libs/kiss/lib/linuxarmv6l/libkiss.a /home/pi/openFrameworks/libs/tess2/lib/linuxarmv6l/libtess2.a   -lz -lgstapp-1.0 -lgstvideo-1.0 -lgstbase-1.0 -lgstreamer-1.0 -ludev -lfontconfig -lfreetype -lsndfile -lopenal -lcurl -lglfw -lrtaudio -lasound -lpulse-simple -lpulse -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lfreeimage -lboost_filesystem -lboost_system -lpugixml -luriparser -lXinerama -lbrcmGLESv2 -lbrcmEGL -lopenmaxil -lbcm_host -lvcos -lvchiq_arm -lpcre -lrt -lX11 -ldl
/usr/bin/ld: obj/linuxarmv6l/Release/src/ofApp.o:(.data.rel.ro+0x30): undefined reference to `ofApp::update()'
/usr/bin/ld: obj/linuxarmv6l/Release/src/ofApp.o:(.data.rel.ro+0x38): undefined reference to `ofApp::exit()'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:405: bin/etal] Error 1
make[1]: Leaving directory '/home/pi/openFrameworks/apps/myApps/etal'
make: *** [/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Error 2
`
this is the last error.. what can I do next? 

Thanks.

**Comment by bakercp** [comment]
That looks like you probably have ofApp::exit() defined in your header .h
file but not in your .cpp file?

---
https://new.christopherbaker.net

**Comment by kimyousuk** [comment]
I used your example([https://github.com/bakercp/ofxSerial/tree/master/examples/intermediate/packet_serial_device/cobs](url)
I did`t add anything.

**Comment by kimyousuk** [comment]
Once again I changed everything and recompiled it. Thank you very much. It was a great help.

**Comment by bakercp** [comment]
So did you get it working?

**Comment by kimyousuk** [comment]
Your example has been compiled successfully, so let's start my coding again. I'm trying to control an Arduino-based 3D printer with gcode with Raspberry Pi. I tried with oFserial, but I'm here because I've been having problems.

**Comment by bakercp** [comment]
Great!  Good luck.

**Comment by kimyousuk** [comment]
Thanks a lot. Have a nice day!
