### ISSUE TITLE
"COMx does not exist" codeblocks and windows 8

### ISSUE THREAD

**Issue by jmarsico** [bakercp/ofxSerial#5]
`device.setup(devicesInfo[x], 9600)`  throws an exception in codeblocks 12 & windows 8: `Exception: Specified port, COMx, does not exist`. 

The port does exist, as it's listed in the previous `listDevices()` call. Is this a codeblocks issue?  I will continue googling.

**Comment by bakercp** [comment]
Hm.  Check also to see if there are any related issues with https://github.com/wjwwood/serial.

The version of https://github.com/wjwwood/serial I have included is slightly (but not too far) out of date.

Can you open the same port with the built-in ofSerial?

**Comment by jmarsico** [comment]
could be this... https://github.com/wjwwood/serial/issues/84  issues with COMx where x >= 10.

**Comment by bakercp** [comment]
Aha -- if you use that notation does it work?

**Comment by jmarsico** [comment]
working on it... `\` in CB does some funky stuff. changing preferences.

**Comment by jmarsico** [comment]
prepending the string with `"\\.\"` works. This causes problems with the compiler, though, as `\` is some shorthand for removing the next character (i think).

regardless, i ended up using:
"string port = "";
port.append("\\\\\\\\.");
port.append("\\\");
port.append(devicesInfo[deviceIndx].getPort());
success = device.setup(port), 9600);"


...FYI... even in markdown "\" does things within a string; hence non-formatted code block above.

**Comment by bakercp** [comment]
Wow.  What a mess! :)

Perhaps you could chime in on the issue upstream (yes slash escapes the following char, so sometimes you have to stack them up in order for the compiler to actually eventually get the one you want :)).

I'd prefer for this to be fixed upstream and then pull it into ofxSerial.

**Comment by bakercp** [comment]
I'm closing this for now, as it was fixed upstream.   Thanks, CB
