### ISSUE TITLE
Send & receive

### ISSUE THREAD

**Issue by natxopedreira** [bakercp/ofxSerial#6]
Hi

Im using your library in a project that im working on. I use it to comunicate with an arduino

I have a listenToArdu and a talkToArdu fuctions in of

The issue that im having its that i can not call the two fuctions, if i send i can receive and viceversa

Im using a SeriaDevice objec
Thanks!

**Comment by bakercp** [comment]
Hi, could you please post some code or error output.

**Comment by natxopedreira** [comment]
Of course

Of code
https://github.com/natxopedreira/TagSlot/blob/master/src/partidaSlot.cpp

Ardu
https://github.com/natxopedreira/TagSlot/blob/master/tagSlot/tagSlot.ino

I dont get any error, its just that i can not talk and listen only one of those

Its curious that if i put the send fuctions in the ardu loop when its receiving i get some data but not always

hope that make sens

Thanks

**Comment by bakercp** [comment]
@natxopedreira Very strange -- I don't see any code errors ... have you tried using a slower baud rate?  115200 is probably faster than needed and sometimes I've seen strange problems with really high speed and the Arduino.  Have you tried it with just a good old 9600 baud connection?

**Comment by natxopedreira** [comment]
Thanks, yes i tried to use a lower baudrate. And get the same, because this was for a current installation i ended out of time and solved that using two arduinos wich its a dirty solution but i find another way

**Comment by natxopedreira** [comment]
I typped wrong, i dont find another way

**Comment by bakercp** [comment]
Hi there, since there was no additional information on this, I'd suggest adding an issue to the upstream serial repository.  Please re-open if it's clear that this is a problem with ofxSerial.
